packages:
  - apps/*
  - docs
  - packages/*
catalog:
  "@callstack/react-theme-provider": ^3.0.9
  "@eslint/js": ^9.10.0
  "@jest/globals": ^29.7.0
  "@reduxjs/toolkit": ^2.2.7
  "@types/node": ^22.13.9
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.4
  "@types/yargs": ^17.0.33
  "@typescript-eslint/eslint-plugin": ^8.5.0
  "@typescript-eslint/parser": ^8.5.0
  "@vitejs/plugin-react": ^4.3.4
  "@wnayes/electron-redux": 2.0.0-alpha.11
  electron: ^35.0.0
  esbuild: ^0.23.1
  eslint: ^9.10.0
  eslint-plugin-prettier: ^5.2.1
  eslint-plugin-react-hooks: 5.1.0-rc-206df66e-20240912
  freedesktop-desktop-entry: ^1.0.0
  freedesktop-icons: ^1.0.0
  globals: ^15.9.0
  jest: ^29.7.0
  prettier: 3.3.3
  react: ^19.0.0
  react-dom: ^19.0.0
  react-error-boundary: ^5.0.0
  react-redux: ^9.2.0
  redux: ^5.0.1
  rfc4648: ^1.5.3
  ts-jest: ^29.2.5
  tslib: ^2.7.0
  turbo: ^2.1.2
  type-fest: ^4.26.1
  typescript: ~5.6.2
  typescript-eslint: ^8.5.0
  vite: ^5.4.5
  vite-node: ^1.6.0
  x11: ^2.3.0
  xdg-user-dir: ^0.0.1
  yargs: ^17.7.2
