packages:
  - apps/*
  - docs
  - packages/*
catalog:
  "@callstack/react-theme-provider": ^3.0.9
  "@jest/globals": ^29.7.0
  "@reduxjs/toolkit": ^2.2.5
  "@types/node": ^20.12.12
  "@types/react": ^18.3.3
  "@types/react-dom": ^18.3.0
  "@types/yargs": ^17.0.32
  "@typescript-eslint/eslint-plugin": ^7.1.1
  "@typescript-eslint/parser": ^7.1.1
  "@vitejs/plugin-react": ^4.3.0
  "@wnayes/electron-redux": 2.0.0-alpha.10
  electron: ^30.0.8
  esbuild: ^0.21.4
  eslint: ^8.57.0
  eslint-config-prettier: ^9.1.0
  eslint-plugin-react-hooks: ^4.6.0
  freedesktop-desktop-entry: ^1.0.0
  freedesktop-icons: ^1.0.0
  jest: ^29.7.0
  prettier: 3.2.5
  react: ^18.3.1
  react-dom: ^18.3.1
  react-error-boundary: ^4.0.13
  react-redux: ^9.1.2
  redux: ^5.0.1
  rfc4648: ^1.5.3
  ts-jest: ^29.1.2
  tslib: ^2.6.2
  turbo: ^1.12.5
  type-fest: ^4.18.3
  typescript: ~5.4.5
  vite: ^5.2.11
  vite-node: ^1.6.0
  x11: ^2.3.0
  xdg-user-dir: ^0.0.1
  yargs: ^17.7.2
