packages:
  - apps/*
  - docs
  - packages/*
catalog:
  "@callstack/react-theme-provider": ^3.0.9
  "@eslint/js": ^9.10.0
  "@jest/globals": ^29.7.0
  "@reduxjs/toolkit": ^2.2.7
  "@types/node": ^20.12.12
  "@types/react": ^18.3.5
  "@types/react-dom": ^18.3.0
  "@types/yargs": ^17.0.33
  "@typescript-eslint/eslint-plugin": ^8.5.0
  "@typescript-eslint/parser": ^8.5.0
  "@vitejs/plugin-react": ^4.3.1
  "@wnayes/electron-redux": 2.0.0-alpha.10
  electron: ^32.1.0
  esbuild: ^0.23.1
  eslint: ^9.10.0
  eslint-plugin-prettier: ^5.2.1
  eslint-plugin-react-hooks: 5.1.0-rc-206df66e-20240912
  freedesktop-desktop-entry: ^1.0.0
  freedesktop-icons: ^1.0.0
  globals: ^15.9.0
  jest: ^29.7.0
  prettier: 3.3.3
  react: ^18.3.1
  react-dom: ^18.3.1
  react-error-boundary: ^4.0.13
  react-redux: ^9.1.2
  redux: ^5.0.1
  rfc4648: ^1.5.3
  ts-jest: ^29.1.2
  tslib: ^2.7.0
  turbo: ^2.1.2
  type-fest: ^4.18.3
  typescript: ~5.4.5
  typescript-eslint: ^8.5.0
  vite: ^5.2.11
  vite-node: ^1.6.0
  x11: ^2.3.0
  xdg-user-dir: ^0.0.1
  yargs: ^17.7.2
